home_page/urls.py
from django.conf.urls import url
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^countries/$',countries,name='countries'),
    url(r'^categories/$',categories,name='categories'),
    url(r'^month/$',month,name='month'),
    url(r'^aboutus/$',aboutus,name='aboutus'),
    url(r'^contactus/$',contactus,name='contactus'),
    url(r'^india/$',india,name='india'),
    url(r'^city_name/(.*)/(.*)/$',city,name='city_name'),
    url(r'^japan/$',japan,name='japan'),
    url(r'^argentina/$',argentina,name='argentina'),
    url(r'^brazil/$',brazil,name='brazil'),
    url(r'^canada/$',canada,name='canada'),
    url(r'^china/$',china,name='china'),
    url(r'^madagascar/$',madagascar,name='madagascar'),
    url(r'^uae/$',uae,name='uae'),
    url(r'^usa/$',usa,name='usa'),
    url(r'^france/$',france,name='france'),
    url(r'^greece/$',greece,name='greece'),
    url(r'^egypt/$',egypt,name='egypt'),
    url(r'^sweden/$',sweden,name='sweden'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sampark/urls.py
from django.conf.urls import url
from .views import *
app_name='sampark'
'''
urlpatterns = [
    url(r'^contact/$',contact,name=contact),
    url(r'^suggest/$',suggest,name=suggest),

]
'''

trip_travel/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from home_page.urls import *
from home_page.views import *
from registration.views import *
from login.views import *
from comment.views import *
from sampark.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$',index,name='index'),
    url(r'^home_page/',include('home_page.urls',namespace='home_page')),
    url(r'^admin/', admin.site.urls),
    url(r'^register/$',register,name='register'),
    url(r'^login/$',user_login,name='user_login'),
    url(r'^logout/$',user_logout,name='logout'),
    url(r'^contact/$',contact,name='contact'),
    url(r'^suggest/$',suggest,name='suggest'),
    url(r'^countries_create/$',CountriesCreateView.as_view(),name='country_create'),
    url(r'^countries_update/(?P<pk>[-\w{}.-]{1,4})$',CountriesUpdateView.as_view(),name='countries_update'),
    url(r'^countries_detail/(?P<pk>[-\w{}.-]{1,4})/$', CountriesDetailView.as_view(), name='detail'),
    url(r'^countries_list/$',CountriesListView.as_view(), name='list'),
    url(r'^countries_delete/(?P<pk>[-\w{}.-]{1,4})$',CountriesDeleteView.as_view(),name='countries_delete'),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comment/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from home_page.models import *

# Create your models here.

class comment(models.Model):

    user = models.ForeignKey(User,blank=True,null=True)
    title=models.CharField(max_length=30)
    comment_box=models.TextField()
    city=models.ForeignKey(Cities,blank=True,null=True)
    date_created = models.DateTimeField(auto_now=True,blank=True,null=True)

    def __unicode__(self):
        return self.title

login/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class user(models.Model):
    username=models.CharField(max_length=50)
    password=models.CharField(max_length=50)

    def __unicode__(self):
        return self.username

login/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout
from django.http import *
from django.shortcuts import *
from django.views.generic import UpdateView,CreateView,DeleteView,DetailView,ListView
from django.core.urlresolvers import reverse,reverse_lazy
from home_page.models import *

# Create your views here.

def user_login(request):
    if request.method=='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate (username=username, password=password)
        if user:
            login(request,user)
            return redirect('index')

        else:
            print("Someone Login and Failed!")
            print("Username:{} and Password:{}".format(username,password))
            return render(request,"login.html",{'invalid':True})

    else:
        return render(request,"login.html")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

class CountriesCreateView(CreateView):
    model= Countries
    fields='__all__'

class CountriesUpdateView(UpdateView):
    fields='__all__'
    model= Countries

class CountriesDeleteView(DeleteView):
    model = Countries
    success_url = reverse_lazy('index')
    context_object_name='country'


class CountriesDetailView(DetailView):
    model=Countries
    template_name='home_page/countries_details.html'
    context_object_name= 'country'


class CountriesListView(ListView):
    model=Countries
    context_object_name= 'countries_list'

templates/Aboutus.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<meta charset="utf-8"/>
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Roboto+Slab" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Mogra" rel="stylesheet">
	<link rel="shortcut icon" type="png" href="{% static 'images/fav.png' %}">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<title>Home</title>
</head>
<body>
	<header class="hed">
		<div class="hed-div">
		<a href="index.html"><img src="{% static 'Images/travel.jpg'%}" alt="Logo" width="150px" class="hed-div-img"><a>
		<nav class="hed-nav">
			<div class="log-reg">
				<ul>
				{% if request.user.is_authenticated %}
				<li><a href="{% url 'logout' %}">Logout</a></li>
				{% else %}
				<li> <a href="{% url 'user_login' %}">Login</a> </li>
				{% endif %}
				<li> <a href="{% url 'register' %}">Register</a> </li>
			</ul>
			</div>
			<ul>
				<li><a href="{% url 'index' %}">Home</a></li>
				<li><a href="{% url 'home_page:countries' %}">Countries</a></li>
				<li><a>Categories</a>
					<ul>
						<li><a href="{% url 'home_page:categories' %}">Type&emsp;</a></li>
						<li><a href="{% url 'home_page:month' %}">Month&nbsp;</a></li>
					</ul>
				</li>
				<li><a href="{% url 'home_page:aboutus' %}">About Us</a></li>
				<li><a>Contact</a>

						<ul>
								<li><a href="{% url 'contact' %}">ContactUs</a></li>
							 	<li><a href="{% url 'suggest' %}">SuggestUs</a></li>
						 </ul>


				</li>
			</ul>
		</nav>
		</div>
	</header>

	<section>
		<div class="about-hed">
			About Us
		</div>
		<div class="about">
			Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
			quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.


			<br><br>
			<h4>Hardware Required:</h4>
			Minimum 1GB RAM,Pentium Dual Core
			<br><br>
			<h4>Software Required:</h4>
			 Windows xp or higher
			<br><br>
			<h4>Front-end:</h4>
			HTML5 and CSS3
			<br><br>
			<h4>Back-end language:</h4>
			Python 2.7
			<br><br>
			<h4>Framework:</h4>
			Django 1.11
			<br><br>
			<h4>Database:</h4>
			Sqlite3
		</div>
		<div class="team-hed">
			TEAM
		</div>
		<div class="team">
			<div class="arpit">
				<h2>Arpit</h2>
				<a href="https://www.linkedin.com/in/arpit-gupta-116a57120"><i class="fa fa-linkedin-square" style="font-size:28px;color:#0077B5;"></i></a>
				<a href="https://www.google.com/+ArpitGupta276"><i class="fa fa-google-plus-circle" style="font-size:28px;color:red"></i></a>
				<br><br>
				Arpit Gupta
			</div>
			<div class="aastha">
				<h2>Aastha</h2>
				<br><br>
				Aastha Kansal
			</div>
			<br><br><br><br><br><br><br><br><br><br><br><br><br>
			<div class="arpit">
				<h2>Jatin Saini</h2>
				<a href="https://www.linkedin.com/in/arpit-gupta-116a57120"><i class="fa fa-linkedin-square" style="font-size:28px;color:#0077B5;"></i></a>
				<a href="https://www.google.com/+ArpitGupta276"><i class="fa fa-google-plus-circle" style="font-size:28px;color:red"></i></a>
				<br><br>
				Jatin Saini
			</div>
			<div class="aastha">
				<h2>Gagan</h2>
				<br><br>
				Gagan
			</div>
		</div>

	</section>

<footer class="foot">

			&copy; copyright 2017 Trip Travel (MCA)

	</footer>

</body>
</html>

templates/Countries.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<meta charset="utf-8"/>
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Roboto+Slab" rel="stylesheet">
	<link rel="shortcut icon" type="png" href="{% static 'images/fav.png' %}">
	<title>Countries</title>
</head>
<body>
	<header class="hed">
		<div class="hed-div">
		<a href="index.html"><img src="{% static 'Images/travel.jpg' %}" alt="Logo" width="150px" class="hed-div-img"><a>
		<nav class="hed-nav">
			<div class="log-reg">
				<ul>
				{% if request.user.is_authenticated %}
				<li><a href="{% url 'logout' %}">Logout</a></li>
				{% else %}
				<li> <a href="{% url 'user_login' %}">Login</a> </li>
				{% endif %}
				<li> <a href="{% url 'register' %}">Register</a> </li>
			</ul>
			</div>
			<ul>
				<li><a href="{% url 'index' %}">Home</a></li>
				<li><a href="{% url 'home_page:countries' %}">Countries</a></li>
				<li><a>Categories</a>
					<ul>
						<li><a href="{% url 'home_page:categories' %}">Type&emsp;</a></li>
						<li><a href="{% url 'home_page:month' %}">Month&nbsp;</a></li>
					</ul>
				</li>
				<li><a href="{% url 'home_page:aboutus' %}">About Us</a></li>
				<li><a>Contact</a>

						<ul>
								<li><a href="{% url 'contact' %}">ContactUs</a></li>
							 	<li><a href="{% url 'suggest' %}">SuggestUs</a></li>
						 </ul>


				</li>
			</ul>
		</nav>
		</div>
	</header>
	<div class="main-div">

		<aside class="continent">
			<h1>Continents</h1>

			<br><br>

			<img src="{% static 'Images/asia.jpg'%}" alt="Asia" width="180px">

			<br><br>

			<label>Asia</label>

			<br><br><hr><br><br><br><br><br>

			<img src="{% static 'Images/europe.jpg'%}" alt="Europe" width="180px">

			<br><br>

			<label>Europe</label>

			<br><br><hr><br><br><br>

			<img src="{% static 'Images/south_america.jpg'%}" alt="South America" width="180px">

			<br><br>

			<label>South America</label>

			<br><br><hr><br><br><br>

			<img src="{% static 'Images/north_america.png'%}" alt="North America" width="180px">

			<br><br>

			<label>North America</label>

			<br><br><hr><br><br><br>

			<img src="{% static 'Images/africa.png'%}" alt="Africa" width="180px">

			<br><br>

			<label>Africa</label>
		</aside>
		<div class="countries">
			<h1>Countries</h1>

			<br><br>

			<a href="{% url 'home_page:india' %}"><img src="{% static 'Images/india.jpg'%}" alt="India" width="150px"></a>
			<a href="{% url 'home_page:china' %}"><img src="{% static 'Images/china.jpg'%}" alt="China" width="180px"></a>
			&emsp; &emsp; &emsp;
			<a href="{% url 'home_page:uae' %}"><img src="{% static 'Images/uae.jpg'%}" alt="UAE" width="180px"></a>
			<a href="{% url 'home_page:japan' %}"><img src="{% static 'Images/japan.png'%}" alt="Japan" width="180px"></a>

			<br>

			&emsp; &emsp;
			<label>India</label>
			&emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&nbsp;
			<label>China</label>
			&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;
			<label>UAE</label>
			&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;
			<label>Japan</label>

			<br><br><hr><br><br>

			<a href="{% url 'home_page:france' %}"><img src="{% static 'Images/france.jpg'%}" alt="France" width="150px"></a>
			&emsp; &emsp;&emsp;
			<a href="{% url 'home_page:greece' %}"><img src="{% static 'Images/greece.png'%}" alt="Greece" width="150px"></a>
			&emsp; &emsp; &emsp; &nbsp;
			<a href="{% url 'home_page:sweden' %}"><img src="{% static 'Images/sweden.png'%}" alt="Sweden" width="150px"></a>

			<br>

			&emsp; &emsp; &nbsp;
			<label>France</label>
			&emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&nbsp;
			<label>Greece</label>
			&emsp; &emsp;  &emsp;  &emsp; &emsp; &emsp;
			<label>Sweden</label>

			<br><br><hr><br><br><br><br><br><br><br><br><br><br>

			<a href="{% url 'home_page:brazil' %}"><img src="{% static 'Images/brazil.png'%}" alt="Brazil" width="150px"></a>
			&emsp; &emsp; &emsp; &emsp; &emsp;
			<a href="{% url 'home_page:argentina' %}"><img src="{% static 'Images/argentina.jpg'%}" alt="Argentina" width="150px"></a>

			<br>

			&emsp; &emsp; &emsp;
			<label>Brazil</label>
			&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &nbsp;
			<label>Argentina</label>

			<br><br><hr><br><br><br><br><br><br><br><br><br><br>

			<a href="{% url 'home_page:usa' %}"><img src="{% static 'Images/usa.jpg' %}" alt="USA" width="150px"></a>
			&emsp; &emsp; &emsp; &emsp; &emsp;
			<a href="{% url 'home_page:canada' %}"><img src="{% static 'Images/canada.jpg' %}" alt="Canada" width="150px"></a>

			<br>

			&emsp; &emsp; &emsp;
			<label>USA</label>
			&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &nbsp;
			<label>Canada</label>

			<br><br><hr><br><br><br><br>

			<a href="{% url 'home_page:egypt' %}"><img src="{% static 'Images/egypt.jpg'%}" alt="Egypt" width="150px"></a>
			&emsp; &emsp; &emsp; &emsp; &emsp; &emsp;
			<a href="{% url 'home_page:madagascar' %}"><img src="{% static 'Images/madagascar.jpg'%}" alt="Madagascar" width="150px"></a>

			<br>

			&emsp; &emsp;
			<label>Egypt</label>
			&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &nbsp;
			<label>Madagascar</label>
		</div>
		</div>
	<footer class="foot">
			&copy; copyright 2017 Trip Travel (MCA)
	</footer>
</body>
</html>

templates/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<meta charset="utf-8"/>
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Roboto+Slab" rel="stylesheet">
	<link rel="shortcut icon" type="png" href="{% static 'images/fav.png' %}">
	<title>Home</title>
</head>
<body>

	<header class="hed">
		<div class="hed-div">
		<a href="index.html"><img src="{% static 'images/travel.jpg' %}" alt="Logo" width="150px" class="hed-div-img"><a>
		<nav class="hed-nav">
			<div class="log-reg">

				<ul>
				{% if request.user.is_authenticated %}
				{% with a=a %}
				<li style="color:#0E90C7;font-weight:bolder;">Welcome: {{ a.username }}</li>
				{% endwith %}
				<li><a href="{% url 'logout' %}">Logout</a></li>
				{% else %}
				<li> <a href="{% url 'user_login' %}">Login</a> </li>
				{% endif %}&emsp;
				<li> <a href="{% url 'register' %}">Register</a> </li>
			</ul>

		</div>

			<ul style="margin-left:135px">
				<li><a href="{% url 'index' %}">Home</a></li>
				<li><a href="{% url 'home_page:countries' %}">Countries</a></li>
				<li><a>Categories</a>
					<ul>
						<li><a href="{% url 'home_page:categories' %}">Type&emsp;</a></li>
						<li><a href="{% url 'home_page:month' %}">Month&nbsp;</a></li>
					</ul>
				</li>
				<li><a href="{% url 'home_page:aboutus' %}">About Us</a></li>
				<li><a>Contact</a>

						<ul>
								<li><a href="{% url 'contact' %}">ContactUs</a></li>
							 	<li><a href="{% url 'suggest' %}">SuggestUs</a></li>
						 </ul>


				</li>
			</ul>

		</nav>
		</div>
	</header>

	<section class="sec">
		<div class="sec-div1">
				<img src="{% static 'Images/home_travel.jpg' %}" alt=travel width="50.5%" class="sec-img1">
				<img src="{% static 'Images/home_travel2.jpg' %}" alt=travel width="49.5%" class="sec-img2">
		</div>


		<div class="sec-div2">
			<h1 style="color: #5c5c8a;">Places in India</h1>
			<br>
			<br>
			<a href="{% url 'home_page:india' %}"><img src="{% static 'Images/beaches.jpg' %}" alt="beaches" width="150px" class="sec-img3"></a>

			&emsp; &emsp; &emsp; &emsp;

			<a href="{% url 'home_page:india' %}"><img src="{% static 'Images/mountains.png' %}" alt="mountains" width="150px"></a>

			&emsp; &emsp; &emsp; &emsp;

			<a href="{% url 'home_page:india' %}"><img src="{% static 'Images/historical.jpg' %}" alt="historical" width="150px"></a>

			&emsp; &emsp; &emsp; &emsp;

			<a href="{% url 'home_page:india' %}"><img src="{% static 'Images/adventure.jpg' %}"Images/ alt="adventure" width="150px" class="sec-img6"></a>

			<br>

			&emsp; &emsp; &nbsp; <label>Beaches</label>

			&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&nbsp; <label>Mountains</label>

			&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; <label>Historical</label>

			&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; <label>Adventure</label>

		</div>
		<br><br><br>
		  {% if user.is_superuser %}
		<div class="super">
			<h2>Edit Tables</h2>
			<br>
			<a href="{% url 'country_create' %}">Create New Country</a>
			&emsp;&emsp;&emsp;
			<a href="{% url 'list' %}">View Exisiting Countries</a>
		</div>
		{% endif %}
	</section>


	<footer class="foot">

			&copy; copyright 2017 Trip Travel (MCA)

	</footer>

</body>
</html>

templates/india.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<meta charset="utf-8"/>
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Roboto+Slab" rel="stylesheet">
	<link rel="shortcut icon" type="png" href="{% static 'images/fav.png' %}">
	<title>Home</title>
</head>

<body>
	<header class="hed">
		<div class="hed-div">
		<a href="index.html"><img src="{% static 'Images/travel.jpg' %}" alt="Logo" width="150px" class="hed-div-img"><a>
		<nav class="hed-nav">
			<div class="log-reg">
				<ul>
				{% if request.user.is_authenticated %}
				<li><a href="{% url 'logout' %}">Logout</a></li>
				{% else %}
				<li> <a href="{% url 'user_login' %}">Login</a> </li>
				{% endif %}
				<li> <a href="{% url 'register' %}">Register</a> </li>
			</ul>
			</div>
			<ul>
				<li><a href="{% url 'index' %}">Home</a></li>
				<li><a href="{% url 'home_page:countries' %}">Countries</a></li>
				<li><a>Categories</a>
					<ul>
						<li><a href="{% url 'home_page:categories' %}">Type&emsp;</a></li>
						<li><a href="{% url 'home_page:month' %}">Month&nbsp;</a></li>
					</ul>
				</li>
				<li><a href="{% url 'home_page:aboutus' %}">About Us</a></li>
				<li><a>Contact</a>

						<ul>
								<li><a href="{% url 'contact' %}">ContactUs</a></li>
							 	<li><a href="{% url 'suggest' %}">SuggestUs</a></li>
						 </ul>


				</li>
			</ul>
		</nav>
	</div>
	</header>

	<div class="main-div">
		{% with j=data %}
		<aside class=side>
			<img src="{{ j.Image.url }}" alt="India">
			<br>
			<h1> {{ j.Name|upper }} <h1>
		</aside>
		<section class="india-sec">
			<div class="para">
				<p>
				<h1>About {{ j.Name }}</h1>
				<br>
				{{ j.About|linebreaks }}
				<br>
				</p>
				{% endwith %}
			</div>

	<div class="tab">
		<button class="tablinks active" onclick="openCity(event, 'Beaches')" >Beaches</button>
    <button class="tablinks" onclick="openCity(event, 'Adventure')">Adventure Sports</button>
    <button class="tablinks" onclick="openCity(event, 'Mountains')">Hill Station</button>
    <button class="tablinks" onclick="openCity(event, 'Historical')">Historical Places</button>
  </div>

  <div id="Beaches" class="tabcontent" style="display:block">
    {% for i in Bdata %}
		<br>
    <h3>{{ i.Name }}</h3>
		<br>
    <img src="{{ i.Image.url }}" alt="Not Found">
		<br><br>
    <p>{{ i.About }}</p>

		<br>
		<br>

		{% if request.user.is_authenticated %}
		<div class="comment">
			<form action="{% url 'home_page:city_name' i.Name data.Name %}" method="post">
					{% csrf_token %}
					<label>Title:</label>
					<br>
					{{ form.title }}
					<br>
					<label>Comment:</label>
					<br>
					{{ form.comment_box }}
					<br><br>
					<input type="submit" value="COMMENT">
				</form>
				</div>

		{% endif %}

		<div class="comment">
		<h2>Comments</h2>

				{% for k in i.comment_set.all %}
				<br>
				<h3>Title: {{ k.title }}</h3>
				Comment: {{ k.comment_box }}
				<br>
				Posted By: {{ k.user.username }} on {{ k.date_created }}
				<hr>
				<br>
				{% endfor %}
				</div>
				</br>
				<hr>
				{% endfor %}

  </div>

  <div id="Adventure" class="tabcontent">
    {% for i in Adata %}
		<br>
    <h3>{{ i.Name }}</h3>
		<br>
    <img src="{{ i.Image.url }}" alt="Not Found">
		<br><br>
    <p>{{ i.About }}</p>
		<br><br>
				{% if request.user.is_authenticated %}
				<div class="comment">
					<form action="{% url 'home_page:city_name' i.Name data.Name %}" method="post">
							{% csrf_token %}
							<label>Title:</label>
							<br>
							{{ form.title }}
							<br>
							<label>Comment:</label>
							<br>
							{{ form.comment_box }}
							<br><br>
							<input type="submit" value="COMMENT">
						</form>
						</div>
				{% endif %}
				<div class="comment">
				<h2>Comments</h2>

						{% for k in i.comment_set.all %}
						<br>
						<h3>Title: {{ k.title }}</h3>
						Comment:{{ k.comment_box }}

						Posted By: {{ k.user.username }} on {{ k.date_created }}
						<hr>
						<br>
						{% endfor %}
						</div>
						</br>
						<hr>
						{% endfor %}

  </div>

  <div id="Mountains" class="tabcontent">
    {% for i in Mdata %}
		<br>
    <h3>{{ i.Name }}</h3>
		<br>
    <img src="{{ i.Image.url }}" alt="Not Found">
		<br><br>
    <p>{{ i.About }}</p>
		<br><br>
		{% if request.user.is_authenticated %}
		<div class="comment">
			<form action="{% url 'home_page:city_name' i.Name data.Name %}" method="post">
					{% csrf_token %}
					<label>Title:</label>
					<br>
					{{ form.title }}
					<br>
					<label>Comment:</label>
					<br>
					{{ form.comment_box }}
					<br><br>
					<input type="submit" value="COMMENT">
				</form>
				</div>
		{% endif %}
		<div class="comment">
		<h2>Comments</h2>

				{% for k in i.comment_set.all %}
				<br>
				<h3>Title: {{ k.title }}</h3>
				Comment: {{ k.comment_box }}

				Posted By: {{ k.user.username }} on {{ k.date_created }}
				<hr>
				<br>
				{% endfor %}
				</div>
				</br>
				<hr>
    {% endfor %}
  </div>

  <div id="Historical" class="tabcontent">
    {% for i in Hdata %}
		<br>
    <h3>{{ i.Name }}</h3>
		<br>
    <img src="{{ i.Image.url }}" alt="Not Found">
		<br><br>
    <p>{{ i.About }}</p>
		<br><br>
		{% if request.user.is_authenticated %}
		<div class="comment">
			<form action="{% url 'home_page:city_name' i.Name data.Name %}" method="post">
					{% csrf_token %}
					<label>Title:</label>
					<br>
					{{ form.title }}
					<br>
					<label>Comment:</label>
					<br>
					{{ form.comment_box }}
					<br><br>
					<input type="submit" value="COMMENT">
				</form>
				</div>
		{% endif %}
		<div class="comment">
		<h2>Comments</h2>

				{% for k in i.comment_set.all %}
				<br>
				<h3>Title: {{ k.title }}</h3>
				Comment: {{ k.comment_box }}

				Posted By: {{ k.user.username }} on {{ k.date_created }}
				<hr>
				<br>
				{% endfor %}
				</div>
				</br>
				<hr>
    {% endfor %}
  </div>

  <script>
  function openCity(evt, cityName) {
      var i, tabcontent, tablinks;
      tabcontent = document.getElementsByClassName("tabcontent");
      for (i = 0; i < tabcontent.length; i++) {
          tabcontent[i].style.display = "none";
      }
      tablinks = document.getElementsByClassName("tablinks");
      for (i = 0; i < tablinks.length; i++) {
          tablinks[i].className = tablinks[i].className.replace(" active", "");
      }
      document.getElementById(cityName).style.display = "block";
      evt.currentTarget.className += " active";
  }
  </script>

			</section>
</div>
	<footer class="foot">

			&copy; copyright 2017 Trip Travel (MCA)

	</footer>
</body>
</html>